CREATE OR REPLACE TYPE PERSONA AS
    OBJECT (
        CODIGO NUMBER,
        NOMBRE VARCHAR2(35),
        DIREC DIRECCION,
        FECHA_NAC DATE,
        MAP MEMBER FUNCTION POR_CODIGO RETURN NUMBER
    );
/

CREATE OR REPLACE TYPE T_ALUMNO AS
    OBJECT (
        AL PERSONA,
        NOTA1 NUMBER,
        NOTA2 NUMBER,
        NOTA3 NUMBER,
        MEMBER FUNCTION NOTAMEDIA RETURN NUMBER,
        MEMBER FUNCTION NOTAMAXIMA RETURN NUMBER
    );
/

--EJERCICIO 4.3
CREATE TABLE ALUMNOS2 OF T_ALUMNO;

/

--insertar datos en oracle directamente
INSERT INTO ALUMNOS2 VALUES(
    PERSONA(1, 'JUAN', DIRECCION('C/ ARANZUEQUE', 'GUADALPUEBLO', 19616), TO_DATE('01/01/2000', 'DD/MM/YYYY')),
    5,
    3,
    9
);

/

--insertar datos en bloque pl/sql
DECLARE
    ALUMNO T_ALUMNO;
BEGIN
    ALUMNO := T_ALUMNO( PERSONA(2, 'PEDRO', DIRECCION('C/ GUADALQUIVIR', 'VALDEISLA', 47446), TO_DATE('07/05/1999', 'DD/MM/YYYY')), 8, 1, 6 );
    INSERT INTO ALUMNOS2 VALUES(
        ALUMNO
    );
END;
/

--insertar datos en bloque pl/sql
DECLARE
    ALUMNO T_ALUMNO;
    DIR1   DIRECCION := DIRECCION('C/ LUIS TOSAR', 'AZUQUECA', 19620);
    DIR2   DIRECCION := DIRECCION('C/ OLIVA', 'ALOVERA', 28805);
    PER1   PERSONA := PERSONA(3, 'LUIS', DIR1, TO_DATE('02/03/1987', 'DD/MM/YYYY'));
BEGIN
    ALUMNO := T_ALUMNO( PER1, 7, 4, 9 );
    INSERT INTO ALUMNOS2 VALUES(
        ALUMNO
    );
    PER1.DIREC := DIR2;
    INSERT INTO ALUMNOS2 VALUES(
        ALUMNO
    );
END;
/

-- INSERTAR FILAS CON BLOQUE PL/SQL
DECLARE
    DIR1 DIRECCION:= DIRECCION ('C/Alcazar 50', 'TOLEDO', 45003);
    DIR2 DIRECCION:= DIRECCION ('C/Gredos 20', 'CACERES', 10394);
    PER2 PERSONA:= PERSONA (8, 'AINHIZE', DIR2, '20/10/1981');
    AL1  T_ALUMNO;
BEGIN
    AL1 := NEW T_ALUMNO (PERSONA (9, 'JESUS', DIR1, '18/10/1987'), 9, 8, 9);
    INSERT INTO ALUMNOS2 VALUES(
        AL1
    ); -- INSERTAR
    AL1 := NEW T_ALUMNO(PER2, 6, 7, 7);
    INSERT INTO ALUMNOS2 VALUES(
        AL1
    ); -- INSERTAR
    COMMIT;
END;
/

--SELECT PARA CONSEGUIR NOMBRE Y NOTA MEDIA DEL ALUMNO
SELECT
    A.AL.NOMBRE,
    ROUND (A.NOTAMEDIA(),
    2)
FROM
    ALUMNOS2 A;

--SELECT PARA CONSEGUIR ALUMNOS DE GUADALAJARA CON NOTA MEDIA MAYOR QUE 6
SELECT
    A.AL.NOMBRE,
    ROUND (A.NOTAMEDIA(),
    2)
FROM
    ALUMNOS2 A
WHERE
    A.NOTAMEDIA()> 6
    AND A.AL.DIREC.CIUDAD='AZUQUECA';

--no tengo Guadalajara en la tabla
--SELECT PARA CONSEGUIR NOMBRE DEL ALUMNO CON LA MAXIMA NOTA MEDIA.
SELECT
    A.AL.NOMBRE,
    ROUND (A.NOTAMEDIA(),
    2)
FROM
    ALUMNOS2 A
WHERE
    A.NOTAMEDIA() = (
        SELECT
            MAX (B.NOTAMEDIA())
        FROM
            ALUMNOS2 B
    );
-- SELECT PARA CONSEGUIR NOMBRE DE ALUMNO CON NOTA MÁS ALTA
SELECT A.AL.NOMBRE, A.NOTAMAXIMA() FROM ALUMNOS2 A WHERE A.NOTAMAXIMA() = (SELECT MAX(B.NOTAMAXIMA()) FROM ALUMNOS2 B);