package datos;
// Generated 10 may 2023 10:53:59 by Hibernate Tools 4.3.6.Final

import java.util.Date;

/**
 * AllergensProducts generated by hbm2java
 */
public class AllergensProducts implements java.io.Serializable {

	private AllergensProductsId id;
	private Allergens allergens;
	private Products products;
	private Date createdAt;
	private Date updatedAt;

	public AllergensProducts() {
	}

	public AllergensProducts(AllergensProductsId id, Allergens allergens, Products products) {
		this.id = id;
		this.allergens = allergens;
		this.products = products;
	}

	public AllergensProducts(AllergensProductsId id, Allergens allergens, Products products, Date createdAt,
			Date updatedAt) {
		this.id = id;
		this.allergens = allergens;
		this.products = products;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public AllergensProductsId getId() {
		return this.id;
	}

	public void setId(AllergensProductsId id) {
		this.id = id;
	}

	public Allergens getAllergens() {
		return this.allergens;
	}

	public void setAllergens(Allergens allergens) {
		this.allergens = allergens;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
