package datos;
// Generated 10 may 2023 10:53:59 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Allergens generated by hbm2java
 */
public class Allergens implements java.io.Serializable {

	private BigInteger id;
	private Date createdAt;
	private String description;
	private String name;
	private Date updatedAt;
	private Set<AllergensProducts> allergensProductses = new HashSet<AllergensProducts>(0);

	public Allergens() {
	}

	public Allergens(BigInteger id, String name) {
		this.id = id;
		this.name = name;
	}

	public Allergens(BigInteger id, Date createdAt, String description, String name, Date updatedAt,
			Set<AllergensProducts> allergensProductses) {
		this.id = id;
		this.createdAt = createdAt;
		this.description = description;
		this.name = name;
		this.updatedAt = updatedAt;
		this.allergensProductses = allergensProductses;
	}

	public BigInteger getId() {
		return this.id;
	}

	public void setId(BigInteger id) {
		this.id = id;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set<AllergensProducts> getAllergensProductses() {
		return this.allergensProductses;
	}

	public void setAllergensProductses(Set<AllergensProducts> allergensProductses) {
		this.allergensProductses = allergensProductses;
	}

}
