package datos;
// Generated 10 may 2023 10:53:59 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;

/**
 * AllergensProductsId generated by hbm2java
 */
public class AllergensProductsId implements java.io.Serializable {

	private BigInteger productId;
	private BigInteger allergenId;

	public AllergensProductsId() {
	}

	public AllergensProductsId(BigInteger productId, BigInteger allergenId) {
		this.productId = productId;
		this.allergenId = allergenId;
	}

	public BigInteger getProductId() {
		return this.productId;
	}

	public void setProductId(BigInteger productId) {
		this.productId = productId;
	}

	public BigInteger getAllergenId() {
		return this.allergenId;
	}

	public void setAllergenId(BigInteger allergenId) {
		this.allergenId = allergenId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AllergensProductsId))
			return false;
		AllergensProductsId castOther = (AllergensProductsId) other;

		return ((this.getProductId() == castOther.getProductId()) || (this.getProductId() != null
				&& castOther.getProductId() != null && this.getProductId().equals(castOther.getProductId())))
				&& ((this.getAllergenId() == castOther.getAllergenId())
						|| (this.getAllergenId() != null && castOther.getAllergenId() != null
								&& this.getAllergenId().equals(castOther.getAllergenId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProductId() == null ? 0 : this.getProductId().hashCode());
		result = 37 * result + (getAllergenId() == null ? 0 : this.getAllergenId().hashCode());
		return result;
	}

}
