package datos;
// Generated 10 may 2023 10:53:59 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;
import java.util.Date;

/**
 * Bookings generated by hbm2java
 */
public class Bookings implements java.io.Serializable {

	private BigInteger id;
	private Tables tables;
	private Turns turns;
	private Users users;
	private Date createdAt;
	private Date fecha;
	private Date updatedAt;

	public Bookings() {
	}

	public Bookings(BigInteger id, Tables tables, Turns turns, Users users, Date fecha) {
		this.id = id;
		this.tables = tables;
		this.turns = turns;
		this.users = users;
		this.fecha = fecha;
	}

	public Bookings(BigInteger id, Tables tables, Turns turns, Users users, Date createdAt, Date fecha,
			Date updatedAt) {
		this.id = id;
		this.tables = tables;
		this.turns = turns;
		this.users = users;
		this.createdAt = createdAt;
		this.fecha = fecha;
		this.updatedAt = updatedAt;
	}

	public BigInteger getId() {
		return this.id;
	}

	public void setId(BigInteger id) {
		this.id = id;
	}

	public Tables getTables() {
		return this.tables;
	}

	public void setTables(Tables tables) {
		this.tables = tables;
	}

	public Turns getTurns() {
		return this.turns;
	}

	public void setTurns(Turns turns) {
		this.turns = turns;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
