package datos;
// Generated 10 may 2023 10:53:59 by Hibernate Tools 4.3.6.Final

import java.util.Date;

/**
 * DishesMenus generated by hbm2java
 */
public class DishesMenus implements java.io.Serializable {

	private DishesMenusId id;
	private Products productsByDishId;
	private Products productsByMenuId;
	private Date createdAt;
	private long orden;
	private Date updatedAt;

	public DishesMenus() {
	}

	public DishesMenus(DishesMenusId id, Products productsByDishId, Products productsByMenuId, long orden) {
		this.id = id;
		this.productsByDishId = productsByDishId;
		this.productsByMenuId = productsByMenuId;
		this.orden = orden;
	}

	public DishesMenus(DishesMenusId id, Products productsByDishId, Products productsByMenuId, Date createdAt,
			long orden, Date updatedAt) {
		this.id = id;
		this.productsByDishId = productsByDishId;
		this.productsByMenuId = productsByMenuId;
		this.createdAt = createdAt;
		this.orden = orden;
		this.updatedAt = updatedAt;
	}

	public DishesMenusId getId() {
		return this.id;
	}

	public void setId(DishesMenusId id) {
		this.id = id;
	}

	public Products getProductsByDishId() {
		return this.productsByDishId;
	}

	public void setProductsByDishId(Products productsByDishId) {
		this.productsByDishId = productsByDishId;
	}

	public Products getProductsByMenuId() {
		return this.productsByMenuId;
	}

	public void setProductsByMenuId(Products productsByMenuId) {
		this.productsByMenuId = productsByMenuId;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public long getOrden() {
		return this.orden;
	}

	public void setOrden(long orden) {
		this.orden = orden;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
