package datos;
// Generated 10 may 2023 10:53:59 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;

/**
 * DishesMenusId generated by hbm2java
 */
public class DishesMenusId implements java.io.Serializable {

	private BigInteger menuId;
	private BigInteger dishId;

	public DishesMenusId() {
	}

	public DishesMenusId(BigInteger menuId, BigInteger dishId) {
		this.menuId = menuId;
		this.dishId = dishId;
	}

	public BigInteger getMenuId() {
		return this.menuId;
	}

	public void setMenuId(BigInteger menuId) {
		this.menuId = menuId;
	}

	public BigInteger getDishId() {
		return this.dishId;
	}

	public void setDishId(BigInteger dishId) {
		this.dishId = dishId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DishesMenusId))
			return false;
		DishesMenusId castOther = (DishesMenusId) other;

		return ((this.getMenuId() == castOther.getMenuId()) || (this.getMenuId() != null
				&& castOther.getMenuId() != null && this.getMenuId().equals(castOther.getMenuId())))
				&& ((this.getDishId() == castOther.getDishId()) || (this.getDishId() != null
						&& castOther.getDishId() != null && this.getDishId().equals(castOther.getDishId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMenuId() == null ? 0 : this.getMenuId().hashCode());
		result = 37 * result + (getDishId() == null ? 0 : this.getDishId().hashCode());
		return result;
	}

}
