package datos;
// Generated 10 may 2023 10:53:59 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private BigInteger id;
	private Date createdAt;
	private Date fecha;
	private Date updatedAt;
	private Set<OrdersProducts> ordersProductses = new HashSet<OrdersProducts>(0);
	private Set<Users> userses = new HashSet<Users>(0);

	public Orders() {
	}

	public Orders(BigInteger id, Date fecha) {
		this.id = id;
		this.fecha = fecha;
	}

	public Orders(BigInteger id, Date createdAt, Date fecha, Date updatedAt, Set<OrdersProducts> ordersProductses,
			Set<Users> userses) {
		this.id = id;
		this.createdAt = createdAt;
		this.fecha = fecha;
		this.updatedAt = updatedAt;
		this.ordersProductses = ordersProductses;
		this.userses = userses;
	}

	public BigInteger getId() {
		return this.id;
	}

	public void setId(BigInteger id) {
		this.id = id;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set<OrdersProducts> getOrdersProductses() {
		return this.ordersProductses;
	}

	public void setOrdersProductses(Set<OrdersProducts> ordersProductses) {
		this.ordersProductses = ordersProductses;
	}

	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
