package datos;
// Generated 10 may 2023 10:53:59 by Hibernate Tools 4.3.6.Final

import java.util.Date;

/**
 * OrdersProducts generated by hbm2java
 */
public class OrdersProducts implements java.io.Serializable {

	private OrdersProductsId id;
	private Orders orders;
	private Products products;
	private Date createdAt;
	private long quantity;
	private Date updatedAt;

	public OrdersProducts() {
	}

	public OrdersProducts(OrdersProductsId id, Orders orders, Products products, long quantity) {
		this.id = id;
		this.orders = orders;
		this.products = products;
		this.quantity = quantity;
	}

	public OrdersProducts(OrdersProductsId id, Orders orders, Products products, Date createdAt, long quantity,
			Date updatedAt) {
		this.id = id;
		this.orders = orders;
		this.products = products;
		this.createdAt = createdAt;
		this.quantity = quantity;
		this.updatedAt = updatedAt;
	}

	public OrdersProductsId getId() {
		return this.id;
	}

	public void setId(OrdersProductsId id) {
		this.id = id;
	}

	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public long getQuantity() {
		return this.quantity;
	}

	public void setQuantity(long quantity) {
		this.quantity = quantity;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
