package datos;
// Generated 10 may 2023 10:53:59 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;
import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

	private BigInteger id;
	private Categories categories;
	private Date createdAt;
	private String description;
	private short forsale;
	private Blob image;
	private String name;
	private double price;
	private String type;
	private Date updatedAt;
	private Set<OrdersProducts> ordersProductses = new HashSet<OrdersProducts>(0);
	private Set<DishesMenus> dishesMenusesForDishId = new HashSet<DishesMenus>(0);
	private Set<ResumenMenus> resumenMenusesForIdMenu = new HashSet<ResumenMenus>(0);
	private Set<AllergensProducts> allergensProductses = new HashSet<AllergensProducts>(0);
	private Set<ResumenMenus> resumenMenusesForIdPlato = new HashSet<ResumenMenus>(0);
	private Set<DishesMenus> dishesMenusesForMenuId = new HashSet<DishesMenus>(0);

	public Products() {
	}

	public Products(BigInteger id, Categories categories, String description, short forsale, String name, double price,
			String type) {
		this.id = id;
		this.categories = categories;
		this.description = description;
		this.forsale = forsale;
		this.name = name;
		this.price = price;
		this.type = type;
	}

	public Products(BigInteger id, Categories categories, Date createdAt, String description, short forsale, Blob image,
			String name, double price, String type, Date updatedAt, Set<OrdersProducts> ordersProductses,
			Set<DishesMenus> dishesMenusesForDishId, Set<ResumenMenus> resumenMenusesForIdMenu,
			Set<AllergensProducts> allergensProductses, Set<ResumenMenus> resumenMenusesForIdPlato,
			Set<DishesMenus> dishesMenusesForMenuId) {
		this.id = id;
		this.categories = categories;
		this.createdAt = createdAt;
		this.description = description;
		this.forsale = forsale;
		this.image = image;
		this.name = name;
		this.price = price;
		this.type = type;
		this.updatedAt = updatedAt;
		this.ordersProductses = ordersProductses;
		this.dishesMenusesForDishId = dishesMenusesForDishId;
		this.resumenMenusesForIdMenu = resumenMenusesForIdMenu;
		this.allergensProductses = allergensProductses;
		this.resumenMenusesForIdPlato = resumenMenusesForIdPlato;
		this.dishesMenusesForMenuId = dishesMenusesForMenuId;
	}

	public BigInteger getId() {
		return this.id;
	}

	public void setId(BigInteger id) {
		this.id = id;
	}

	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public short getForsale() {
		return this.forsale;
	}

	public void setForsale(short forsale) {
		this.forsale = forsale;
	}

	public Blob getImage() {
		return this.image;
	}

	public void setImage(Blob image) {
		this.image = image;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set<OrdersProducts> getOrdersProductses() {
		return this.ordersProductses;
	}

	public void setOrdersProductses(Set<OrdersProducts> ordersProductses) {
		this.ordersProductses = ordersProductses;
	}

	public Set<DishesMenus> getDishesMenusesForDishId() {
		return this.dishesMenusesForDishId;
	}

	public void setDishesMenusesForDishId(Set<DishesMenus> dishesMenusesForDishId) {
		this.dishesMenusesForDishId = dishesMenusesForDishId;
	}

	public Set<ResumenMenus> getResumenMenusesForIdMenu() {
		return this.resumenMenusesForIdMenu;
	}

	public void setResumenMenusesForIdMenu(Set<ResumenMenus> resumenMenusesForIdMenu) {
		this.resumenMenusesForIdMenu = resumenMenusesForIdMenu;
	}

	public Set<AllergensProducts> getAllergensProductses() {
		return this.allergensProductses;
	}

	public void setAllergensProductses(Set<AllergensProducts> allergensProductses) {
		this.allergensProductses = allergensProductses;
	}

	public Set<ResumenMenus> getResumenMenusesForIdPlato() {
		return this.resumenMenusesForIdPlato;
	}

	public void setResumenMenusesForIdPlato(Set<ResumenMenus> resumenMenusesForIdPlato) {
		this.resumenMenusesForIdPlato = resumenMenusesForIdPlato;
	}

	public Set<DishesMenus> getDishesMenusesForMenuId() {
		return this.dishesMenusesForMenuId;
	}

	public void setDishesMenusesForMenuId(Set<DishesMenus> dishesMenusesForMenuId) {
		this.dishesMenusesForMenuId = dishesMenusesForMenuId;
	}

}
