package datos;
// Generated 10 may 2023 10:53:59 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;

/**
 * ResumenMenus generated by hbm2java
 */
public class ResumenMenus implements java.io.Serializable {

	private ResumenMenusId id;
	private Products productsByIdMenu;
	private Products productsByIdPlato;
	private String nombreMenu;
	private BigInteger orden;
	private String nombrePlato;
	private String alergenos;

	public ResumenMenus() {
	}

	public ResumenMenus(ResumenMenusId id, Products productsByIdMenu, Products productsByIdPlato, String nombreMenu,
			BigInteger orden, String nombrePlato, String alergenos) {
		this.id = id;
		this.productsByIdMenu = productsByIdMenu;
		this.productsByIdPlato = productsByIdPlato;
		this.nombreMenu = nombreMenu;
		this.orden = orden;
		this.nombrePlato = nombrePlato;
		this.alergenos = alergenos;
	}

	public ResumenMenusId getId() {
		return this.id;
	}

	public void setId(ResumenMenusId id) {
		this.id = id;
	}

	public Products getProductsByIdMenu() {
		return this.productsByIdMenu;
	}

	public void setProductsByIdMenu(Products productsByIdMenu) {
		this.productsByIdMenu = productsByIdMenu;
	}

	public Products getProductsByIdPlato() {
		return this.productsByIdPlato;
	}

	public void setProductsByIdPlato(Products productsByIdPlato) {
		this.productsByIdPlato = productsByIdPlato;
	}

	public String getNombreMenu() {
		return this.nombreMenu;
	}

	public void setNombreMenu(String nombreMenu) {
		this.nombreMenu = nombreMenu;
	}

	public BigInteger getOrden() {
		return this.orden;
	}

	public void setOrden(BigInteger orden) {
		this.orden = orden;
	}

	public String getNombrePlato() {
		return this.nombrePlato;
	}

	public void setNombrePlato(String nombrePlato) {
		this.nombrePlato = nombrePlato;
	}

	public String getAlergenos() {
		return this.alergenos;
	}

	public void setAlergenos(String alergenos) {
		this.alergenos = alergenos;
	}

}
