package datos;
// Generated 10 may 2023 10:53:59 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;

/**
 * ResumenMenusId generated by hbm2java
 */
public class ResumenMenusId implements java.io.Serializable {

	private BigInteger idMenu;
	private BigInteger idPlato;

	public ResumenMenusId() {
	}

	public ResumenMenusId(BigInteger idMenu, BigInteger idPlato) {
		this.idMenu = idMenu;
		this.idPlato = idPlato;
	}

	public BigInteger getIdMenu() {
		return this.idMenu;
	}

	public void setIdMenu(BigInteger idMenu) {
		this.idMenu = idMenu;
	}

	public BigInteger getIdPlato() {
		return this.idPlato;
	}

	public void setIdPlato(BigInteger idPlato) {
		this.idPlato = idPlato;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResumenMenusId))
			return false;
		ResumenMenusId castOther = (ResumenMenusId) other;

		return ((this.getIdMenu() == castOther.getIdMenu()) || (this.getIdMenu() != null
				&& castOther.getIdMenu() != null && this.getIdMenu().equals(castOther.getIdMenu())))
				&& ((this.getIdPlato() == castOther.getIdPlato()) || (this.getIdPlato() != null
						&& castOther.getIdPlato() != null && this.getIdPlato().equals(castOther.getIdPlato())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdMenu() == null ? 0 : this.getIdMenu().hashCode());
		result = 37 * result + (getIdPlato() == null ? 0 : this.getIdPlato().hashCode());
		return result;
	}

}
