package datos;
// Generated 10 may 2023 10:53:59 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tables generated by hbm2java
 */
public class Tables implements java.io.Serializable {

	private BigInteger id;
	private Date createdAt;
	private String name;
	private long tamanyo;
	private Date updatedAt;
	private Set<Bookings> bookingses = new HashSet<Bookings>(0);

	public Tables() {
	}

	public Tables(BigInteger id, String name, long tamanyo) {
		this.id = id;
		this.name = name;
		this.tamanyo = tamanyo;
	}

	public Tables(BigInteger id, Date createdAt, String name, long tamanyo, Date updatedAt, Set<Bookings> bookingses) {
		this.id = id;
		this.createdAt = createdAt;
		this.name = name;
		this.tamanyo = tamanyo;
		this.updatedAt = updatedAt;
		this.bookingses = bookingses;
	}

	public BigInteger getId() {
		return this.id;
	}

	public void setId(BigInteger id) {
		this.id = id;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public long getTamanyo() {
		return this.tamanyo;
	}

	public void setTamanyo(long tamanyo) {
		this.tamanyo = tamanyo;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set<Bookings> getBookingses() {
		return this.bookingses;
	}

	public void setBookingses(Set<Bookings> bookingses) {
		this.bookingses = bookingses;
	}

}
