package datos;
// Generated 10 may 2023 10:53:59 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Turns generated by hbm2java
 */
public class Turns implements java.io.Serializable {

	private BigInteger id;
	private Date createdAt;
	private String fin;
	private String name;
	private String inicio;
	private Date updatedAt;
	private Set<Bookings> bookingses = new HashSet<Bookings>(0);

	public Turns() {
	}

	public Turns(BigInteger id, String fin, String name, String inicio) {
		this.id = id;
		this.fin = fin;
		this.name = name;
		this.inicio = inicio;
	}

	public Turns(BigInteger id, Date createdAt, String fin, String name, String inicio, Date updatedAt,
			Set<Bookings> bookingses) {
		this.id = id;
		this.createdAt = createdAt;
		this.fin = fin;
		this.name = name;
		this.inicio = inicio;
		this.updatedAt = updatedAt;
		this.bookingses = bookingses;
	}

	public BigInteger getId() {
		return this.id;
	}

	public void setId(BigInteger id) {
		this.id = id;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public String getFin() {
		return this.fin;
	}

	public void setFin(String fin) {
		this.fin = fin;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getInicio() {
		return this.inicio;
	}

	public void setInicio(String inicio) {
		this.inicio = inicio;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set<Bookings> getBookingses() {
		return this.bookingses;
	}

	public void setBookingses(Set<Bookings> bookingses) {
		this.bookingses = bookingses;
	}

}
