package datos;
// Generated 10 may 2023 10:53:59 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private BigInteger id;
	private Orders orders;
	private Date createdAt;
	private String email;
	private Date emailVerifiedAt;
	private String name;
	private String password;
	private String rememberToken;
	private Date updatedAt;
	private Set<Bookings> bookingses = new HashSet<Bookings>(0);

	public Users() {
	}

	public Users(BigInteger id, Orders orders, String email, String name, String password) {
		this.id = id;
		this.orders = orders;
		this.email = email;
		this.name = name;
		this.password = password;
	}

	public Users(BigInteger id, Orders orders, Date createdAt, String email, Date emailVerifiedAt, String name,
			String password, String rememberToken, Date updatedAt, Set<Bookings> bookingses) {
		this.id = id;
		this.orders = orders;
		this.createdAt = createdAt;
		this.email = email;
		this.emailVerifiedAt = emailVerifiedAt;
		this.name = name;
		this.password = password;
		this.rememberToken = rememberToken;
		this.updatedAt = updatedAt;
		this.bookingses = bookingses;
	}

	public BigInteger getId() {
		return this.id;
	}

	public void setId(BigInteger id) {
		this.id = id;
	}

	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getEmailVerifiedAt() {
		return this.emailVerifiedAt;
	}

	public void setEmailVerifiedAt(Date emailVerifiedAt) {
		this.emailVerifiedAt = emailVerifiedAt;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRememberToken() {
		return this.rememberToken;
	}

	public void setRememberToken(String rememberToken) {
		this.rememberToken = rememberToken;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set<Bookings> getBookingses() {
		return this.bookingses;
	}

	public void setBookingses(Set<Bookings> bookingses) {
		this.bookingses = bookingses;
	}

}
