package datos;
// Generated 28 dic 2022 19:02:10 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ciclistas generated by hbm2java
 */
public class Ciclistas implements java.io.Serializable {

	private BigInteger codigociclista;
	private Equipos equipos;
	private Ciclistas ciclistas;
	private String nombreciclista;
	private Date fechanacimiento;
	private BigDecimal peso;
	private Set<Lleva> llevas = new HashSet<Lleva>(0);
	private Set<ResumenCamisetas> resumenCamisetases = new HashSet<ResumenCamisetas>(0);
	private Set<Ciclistas> ciclistases = new HashSet<Ciclistas>(0);
	private Set<Tramospuertos> tramospuertoses = new HashSet<Tramospuertos>(0);
	private Set<Etapas> etapases = new HashSet<Etapas>(0);

	public Ciclistas() {
	}

	public Ciclistas(BigInteger codigociclista, Equipos equipos, String nombreciclista, Date fechanacimiento,
			BigDecimal peso) {
		this.codigociclista = codigociclista;
		this.equipos = equipos;
		this.nombreciclista = nombreciclista;
		this.fechanacimiento = fechanacimiento;
		this.peso = peso;
	}

	public Ciclistas(BigInteger codigociclista, Equipos equipos, Ciclistas ciclistas, String nombreciclista,
			Date fechanacimiento, BigDecimal peso, Set<Lleva> llevas, Set<ResumenCamisetas> resumenCamisetases,
			Set<Ciclistas> ciclistases, Set<Tramospuertos> tramospuertoses, Set<Etapas> etapases) {
		this.codigociclista = codigociclista;
		this.equipos = equipos;
		this.ciclistas = ciclistas;
		this.nombreciclista = nombreciclista;
		this.fechanacimiento = fechanacimiento;
		this.peso = peso;
		this.llevas = llevas;
		this.resumenCamisetases = resumenCamisetases;
		this.ciclistases = ciclistases;
		this.tramospuertoses = tramospuertoses;
		this.etapases = etapases;
	}

	public BigInteger getCodigociclista() {
		return this.codigociclista;
	}

	public void setCodigociclista(BigInteger codigociclista) {
		this.codigociclista = codigociclista;
	}

	public Equipos getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Equipos equipos) {
		this.equipos = equipos;
	}

	public Ciclistas getCiclistas() {
		return this.ciclistas;
	}

	public void setCiclistas(Ciclistas ciclistas) {
		this.ciclistas = ciclistas;
	}

	public String getNombreciclista() {
		return this.nombreciclista;
	}

	public void setNombreciclista(String nombreciclista) {
		this.nombreciclista = nombreciclista;
	}

	public Date getFechanacimiento() {
		return this.fechanacimiento;
	}

	public void setFechanacimiento(Date fechanacimiento) {
		this.fechanacimiento = fechanacimiento;
	}

	public BigDecimal getPeso() {
		return this.peso;
	}

	public void setPeso(BigDecimal peso) {
		this.peso = peso;
	}

	public Set<Lleva> getLlevas() {
		return this.llevas;
	}

	public void setLlevas(Set<Lleva> llevas) {
		this.llevas = llevas;
	}

	public Set<ResumenCamisetas> getResumenCamisetases() {
		return this.resumenCamisetases;
	}

	public void setResumenCamisetases(Set<ResumenCamisetas> resumenCamisetases) {
		this.resumenCamisetases = resumenCamisetases;
	}

	public Set<Ciclistas> getCiclistases() {
		return this.ciclistases;
	}

	public void setCiclistases(Set<Ciclistas> ciclistases) {
		this.ciclistases = ciclistases;
	}

	public Set<Tramospuertos> getTramospuertoses() {
		return this.tramospuertoses;
	}

	public void setTramospuertoses(Set<Tramospuertos> tramospuertoses) {
		this.tramospuertoses = tramospuertoses;
	}

	public Set<Etapas> getEtapases() {
		return this.etapases;
	}

	public void setEtapases(Set<Etapas> etapases) {
		this.etapases = etapases;
	}

}
