package datos;
// Generated 28 dic 2022 19:02:10 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Equipos generated by hbm2java
 */
public class Equipos implements java.io.Serializable {

	private BigInteger codigoequipo;
	private String nombreequipo;
	private String director;
	private String pais;
	private Set<ResumenCamisetas> resumenCamisetases = new HashSet<ResumenCamisetas>(0);
	private Set<Ciclistas> ciclistases = new HashSet<Ciclistas>(0);

	public Equipos() {
	}

	public Equipos(BigInteger codigoequipo, String nombreequipo, String director, String pais) {
		this.codigoequipo = codigoequipo;
		this.nombreequipo = nombreequipo;
		this.director = director;
		this.pais = pais;
	}

	public Equipos(BigInteger codigoequipo, String nombreequipo, String director, String pais,
			Set<ResumenCamisetas> resumenCamisetases, Set<Ciclistas> ciclistases) {
		this.codigoequipo = codigoequipo;
		this.nombreequipo = nombreequipo;
		this.director = director;
		this.pais = pais;
		this.resumenCamisetases = resumenCamisetases;
		this.ciclistases = ciclistases;
	}

	public BigInteger getCodigoequipo() {
		return this.codigoequipo;
	}

	public void setCodigoequipo(BigInteger codigoequipo) {
		this.codigoequipo = codigoequipo;
	}

	public String getNombreequipo() {
		return this.nombreequipo;
	}

	public void setNombreequipo(String nombreequipo) {
		this.nombreequipo = nombreequipo;
	}

	public String getDirector() {
		return this.director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public Set<ResumenCamisetas> getResumenCamisetases() {
		return this.resumenCamisetases;
	}

	public void setResumenCamisetases(Set<ResumenCamisetas> resumenCamisetases) {
		this.resumenCamisetases = resumenCamisetases;
	}

	public Set<Ciclistas> getCiclistases() {
		return this.ciclistases;
	}

	public void setCiclistases(Set<Ciclistas> ciclistases) {
		this.ciclistases = ciclistases;
	}

}
