package datos;
// Generated 28 dic 2022 19:02:10 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Etapas generated by hbm2java
 */
public class Etapas implements java.io.Serializable {

	private BigInteger codigoetapa;
	private Ciclistas ciclistas;
	private String tipoetapa;
	private String fechasalida;
	private String pobsalida;
	private String pobllegada;
	private BigDecimal km;
	private Set<Lleva> llevas = new HashSet<Lleva>(0);
	private Set<Tramospuertos> tramospuertoses = new HashSet<Tramospuertos>(0);

	public Etapas() {
	}

	public Etapas(BigInteger codigoetapa, Ciclistas ciclistas, String tipoetapa, String fechasalida, String pobsalida,
			String pobllegada, BigDecimal km) {
		this.codigoetapa = codigoetapa;
		this.ciclistas = ciclistas;
		this.tipoetapa = tipoetapa;
		this.fechasalida = fechasalida;
		this.pobsalida = pobsalida;
		this.pobllegada = pobllegada;
		this.km = km;
	}

	public Etapas(BigInteger codigoetapa, Ciclistas ciclistas, String tipoetapa, String fechasalida, String pobsalida,
			String pobllegada, BigDecimal km, Set<Lleva> llevas, Set<Tramospuertos> tramospuertoses) {
		this.codigoetapa = codigoetapa;
		this.ciclistas = ciclistas;
		this.tipoetapa = tipoetapa;
		this.fechasalida = fechasalida;
		this.pobsalida = pobsalida;
		this.pobllegada = pobllegada;
		this.km = km;
		this.llevas = llevas;
		this.tramospuertoses = tramospuertoses;
	}

	public BigInteger getCodigoetapa() {
		return this.codigoetapa;
	}

	public void setCodigoetapa(BigInteger codigoetapa) {
		this.codigoetapa = codigoetapa;
	}

	public Ciclistas getCiclistas() {
		return this.ciclistas;
	}

	public void setCiclistas(Ciclistas ciclistas) {
		this.ciclistas = ciclistas;
	}

	public String getTipoetapa() {
		return this.tipoetapa;
	}

	public void setTipoetapa(String tipoetapa) {
		this.tipoetapa = tipoetapa;
	}

	public String getFechasalida() {
		return this.fechasalida;
	}

	public void setFechasalida(String fechasalida) {
		this.fechasalida = fechasalida;
	}

	public String getPobsalida() {
		return this.pobsalida;
	}

	public void setPobsalida(String pobsalida) {
		this.pobsalida = pobsalida;
	}

	public String getPobllegada() {
		return this.pobllegada;
	}

	public void setPobllegada(String pobllegada) {
		this.pobllegada = pobllegada;
	}

	public BigDecimal getKm() {
		return this.km;
	}

	public void setKm(BigDecimal km) {
		this.km = km;
	}

	public Set<Lleva> getLlevas() {
		return this.llevas;
	}

	public void setLlevas(Set<Lleva> llevas) {
		this.llevas = llevas;
	}

	public Set<Tramospuertos> getTramospuertoses() {
		return this.tramospuertoses;
	}

	public void setTramospuertoses(Set<Tramospuertos> tramospuertoses) {
		this.tramospuertoses = tramospuertoses;
	}

}
