package datos;
// Generated 28 dic 2022 19:02:10 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;

/**
 * NuevasCamisetas generated by hbm2java
 */
public class NuevasCamisetas implements java.io.Serializable {

	private BigInteger codigocamiseta;
	private String tipo;
	private String color;
	private BigInteger importepremio;

	public NuevasCamisetas() {
	}

	public NuevasCamisetas(BigInteger codigocamiseta, String tipo, String color, BigInteger importepremio) {
		this.codigocamiseta = codigocamiseta;
		this.tipo = tipo;
		this.color = color;
		this.importepremio = importepremio;
	}

	public BigInteger getCodigocamiseta() {
		return this.codigocamiseta;
	}

	public void setCodigocamiseta(BigInteger codigocamiseta) {
		this.codigocamiseta = codigocamiseta;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public BigInteger getImportepremio() {
		return this.importepremio;
	}

	public void setImportepremio(BigInteger importepremio) {
		this.importepremio = importepremio;
	}

}
