package datos;
// Generated 28 dic 2022 19:02:10 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;

/**
 * ResumenCamisetas generated by hbm2java
 */
public class ResumenCamisetas implements java.io.Serializable {

	private ResumenCamisetasId id;
	private Equipos equipos;
	private Ciclistas ciclistas;
	private Camisetas camisetas;
	private BigInteger numveces;
	private BigInteger importepremio;

	public ResumenCamisetas() {
	}

	public ResumenCamisetas(ResumenCamisetasId id, Equipos equipos, Ciclistas ciclistas, Camisetas camisetas,
			BigInteger numveces, BigInteger importepremio) {
		this.id = id;
		this.equipos = equipos;
		this.ciclistas = ciclistas;
		this.camisetas = camisetas;
		this.numveces = numveces;
		this.importepremio = importepremio;
	}

	public ResumenCamisetasId getId() {
		return this.id;
	}

	public void setId(ResumenCamisetasId id) {
		this.id = id;
	}

	public Equipos getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Equipos equipos) {
		this.equipos = equipos;
	}

	public Ciclistas getCiclistas() {
		return this.ciclistas;
	}

	public void setCiclistas(Ciclistas ciclistas) {
		this.ciclistas = ciclistas;
	}

	public Camisetas getCamisetas() {
		return this.camisetas;
	}

	public void setCamisetas(Camisetas camisetas) {
		this.camisetas = camisetas;
	}

	public BigInteger getNumveces() {
		return this.numveces;
	}

	public void setNumveces(BigInteger numveces) {
		this.numveces = numveces;
	}

	public BigInteger getImportepremio() {
		return this.importepremio;
	}

	public void setImportepremio(BigInteger importepremio) {
		this.importepremio = importepremio;
	}

}
