--------------------------------------------------------
-- Archivo creado  - sábado-abril-23-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table VUELO
--------------------------------------------------------

  CREATE TABLE "VUELOS"."VUELO" 
   (	"IDENTIFICADOR" VARCHAR2(10 BYTE), 
	"AEROPUERTO_ORIGEN" VARCHAR2(10 BYTE), 
	"AEROPUERTO_DESTINO" VARCHAR2(10 BYTE), 
	"TIPO_VUELO" VARCHAR2(15 BYTE), 
	"FECHA_VUELO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into VUELOS.VUELO
SET DEFINE OFF;
Insert into VUELOS.VUELO (IDENTIFICADOR,AEROPUERTO_ORIGEN,AEROPUERTO_DESTINO,TIPO_VUELO,FECHA_VUELO) values ('BRU-1234','BRU EBBR','CPH EKCH','CHARTER',to_date('13/03/16','DD/MM/RR'));
Insert into VUELOS.VUELO (IDENTIFICADOR,AEROPUERTO_ORIGEN,AEROPUERTO_DESTINO,TIPO_VUELO,FECHA_VUELO) values ('BRU-2222','BRU EBBR','MAD LEMD','DIRECTO',to_date('14/03/16','DD/MM/RR'));
Insert into VUELOS.VUELO (IDENTIFICADOR,AEROPUERTO_ORIGEN,AEROPUERTO_DESTINO,TIPO_VUELO,FECHA_VUELO) values ('KLM-2343','BRU EBBR','PMI LEPA','DIRECTO',to_date('13/03/16','DD/MM/RR'));
Insert into VUELOS.VUELO (IDENTIFICADOR,AEROPUERTO_ORIGEN,AEROPUERTO_DESTINO,TIPO_VUELO,FECHA_VUELO) values ('IBE-762','MAD LEMD','HEL EFHK','DOMÉSTICO',to_date('07/04/16','DD/MM/RR'));
Insert into VUELOS.VUELO (IDENTIFICADOR,AEROPUERTO_ORIGEN,AEROPUERTO_DESTINO,TIPO_VUELO,FECHA_VUELO) values ('IBE-789','MAD LEMD','GWY EICM','DIRECTO',to_date('10/05/16','DD/MM/RR'));
Insert into VUELOS.VUELO (IDENTIFICADOR,AEROPUERTO_ORIGEN,AEROPUERTO_DESTINO,TIPO_VUELO,FECHA_VUELO) values ('AVI-ASD','MAD LEMD','OSL ENGM','LARGO RECORRIDO',to_date('08/04/16','DD/MM/RR'));
Insert into VUELOS.VUELO (IDENTIFICADOR,AEROPUERTO_ORIGEN,AEROPUERTO_DESTINO,TIPO_VUELO,FECHA_VUELO) values ('AVI-345','MAD LEMD','BRU EBBR','LARGO RECORRIDO',to_date('23/03/16','DD/MM/RR'));
Insert into VUELOS.VUELO (IDENTIFICADOR,AEROPUERTO_ORIGEN,AEROPUERTO_DESTINO,TIPO_VUELO,FECHA_VUELO) values ('DEL-456','MAD LEMD','PRG LKPR','LARGO RECORRIDO',to_date('17/05/16','DD/MM/RR'));
Insert into VUELOS.VUELO (IDENTIFICADOR,AEROPUERTO_ORIGEN,AEROPUERTO_DESTINO,TIPO_VUELO,FECHA_VUELO) values ('DEL-34','CPH EKCH','BRU EBBR','DOMÉSTICO',to_date('27/05/16','DD/MM/RR'));
Insert into VUELOS.VUELO (IDENTIFICADOR,AEROPUERTO_ORIGEN,AEROPUERTO_DESTINO,TIPO_VUELO,FECHA_VUELO) values ('KLM-332','CPH EKCH','HEL EFHK','DIRECTO',to_date('24/05/16','DD/MM/RR'));
Insert into VUELOS.VUELO (IDENTIFICADOR,AEROPUERTO_ORIGEN,AEROPUERTO_DESTINO,TIPO_VUELO,FECHA_VUELO) values ('IBE-212','CPH EKCH','RL  EBCI','CHARTER',to_date('09/04/16','DD/MM/RR'));
Insert into VUELOS.VUELO (IDENTIFICADOR,AEROPUERTO_ORIGEN,AEROPUERTO_DESTINO,TIPO_VUELO,FECHA_VUELO) values ('QAT-224','CPH EKCH','PRG LKPR','CHARTER',to_date('28/03/16','DD/MM/RR'));
Insert into VUELOS.VUELO (IDENTIFICADOR,AEROPUERTO_ORIGEN,AEROPUERTO_DESTINO,TIPO_VUELO,FECHA_VUELO) values ('KLM-78','CPH EKCH','MAD LEMD','DOMÉSTICO',to_date('13/05/16','DD/MM/RR'));
Insert into VUELOS.VUELO (IDENTIFICADOR,AEROPUERTO_ORIGEN,AEROPUERTO_DESTINO,TIPO_VUELO,FECHA_VUELO) values ('IBE-234','PMI LEPA','HEL EFHK','DOMÉSTICO',to_date('17/04/16','DD/MM/RR'));
Insert into VUELOS.VUELO (IDENTIFICADOR,AEROPUERTO_ORIGEN,AEROPUERTO_DESTINO,TIPO_VUELO,FECHA_VUELO) values ('RYA-22','PMI LEPA','GWY EICM','CHARTER',to_date('16/03/16','DD/MM/RR'));
Insert into VUELOS.VUELO (IDENTIFICADOR,AEROPUERTO_ORIGEN,AEROPUERTO_DESTINO,TIPO_VUELO,FECHA_VUELO) values ('RYA-230','PMI LEPA','OSL ENGM','CHARTER',to_date('02/04/16','DD/MM/RR'));
Insert into VUELOS.VUELO (IDENTIFICADOR,AEROPUERTO_ORIGEN,AEROPUERTO_DESTINO,TIPO_VUELO,FECHA_VUELO) values ('QAT-900','PMI LEPA','MAD LEMD','REGULAR',to_date('14/05/16','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index PKVUELO
--------------------------------------------------------

  CREATE UNIQUE INDEX "VUELOS"."PKVUELO" ON "VUELOS"."VUELO" ("IDENTIFICADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table VUELO
--------------------------------------------------------

  ALTER TABLE "VUELOS"."VUELO" ADD CONSTRAINT "PKVUELO" PRIMARY KEY ("IDENTIFICADOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VUELOS"."VUELO" ADD CONSTRAINT "CKTIPOVUELO" CHECK ( TIPO_VUELO IN ('CHARTER', 'DIRECTO', 'DOMÉSTICO', 'LARGO RECORRIDO', 'LOW COST', 'REGULAR')) ENABLE;
  ALTER TABLE "VUELOS"."VUELO" MODIFY ("IDENTIFICADOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table VUELO
--------------------------------------------------------

  ALTER TABLE "VUELOS"."VUELO" ADD CONSTRAINT "ESDESTINO" FOREIGN KEY ("AEROPUERTO_DESTINO")
	  REFERENCES "VUELOS"."AEROPUERTO" ("CODAEROPUERTO") ENABLE;
  ALTER TABLE "VUELOS"."VUELO" ADD CONSTRAINT "ESORIGEN" FOREIGN KEY ("AEROPUERTO_ORIGEN")
	  REFERENCES "VUELOS"."AEROPUERTO" ("CODAEROPUERTO") ENABLE;
