package datos;
// Generated 23 nov 2022 13:48:30 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;

/**
 * Partidos generated by hbm2java
 */
public class Partidos implements java.io.Serializable {

	private BigInteger codigo;
	private Equipos equiposByEquipoLocal;
	private Equipos equiposByEquipoVisitante;
	private Integer puntosLocal;
	private Integer puntosVisitante;
	private String temporada;

	public Partidos() {
	}

	public Partidos(BigInteger codigo) {
		this.codigo = codigo;
	}

	public Partidos(BigInteger codigo, Equipos equiposByEquipoLocal, Equipos equiposByEquipoVisitante,
			Integer puntosLocal, Integer puntosVisitante, String temporada) {
		this.codigo = codigo;
		this.equiposByEquipoLocal = equiposByEquipoLocal;
		this.equiposByEquipoVisitante = equiposByEquipoVisitante;
		this.puntosLocal = puntosLocal;
		this.puntosVisitante = puntosVisitante;
		this.temporada = temporada;
	}

	public BigInteger getCodigo() {
		return this.codigo;
	}

	public void setCodigo(BigInteger codigo) {
		this.codigo = codigo;
	}

	public Equipos getEquiposByEquipoLocal() {
		return this.equiposByEquipoLocal;
	}

	public void setEquiposByEquipoLocal(Equipos equiposByEquipoLocal) {
		this.equiposByEquipoLocal = equiposByEquipoLocal;
	}

	public Equipos getEquiposByEquipoVisitante() {
		return this.equiposByEquipoVisitante;
	}

	public void setEquiposByEquipoVisitante(Equipos equiposByEquipoVisitante) {
		this.equiposByEquipoVisitante = equiposByEquipoVisitante;
	}

	public Integer getPuntosLocal() {
		return this.puntosLocal;
	}

	public void setPuntosLocal(Integer puntosLocal) {
		this.puntosLocal = puntosLocal;
	}

	public Integer getPuntosVisitante() {
		return this.puntosVisitante;
	}

	public void setPuntosVisitante(Integer puntosVisitante) {
		this.puntosVisitante = puntosVisitante;
	}

	public String getTemporada() {
		return this.temporada;
	}

	public void setTemporada(String temporada) {
		this.temporada = temporada;
	}

}
