package datos;
// Generated 9 may 2023 17:23:53 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Alumnos generated by hbm2java
 */
public class Alumnos implements java.io.Serializable {

	private BigInteger numAlumno;
	private Cursos cursos;
	private String nombre;
	private String direccion;
	private String tlf;
	private BigDecimal notaMedia;
	private Set<Evaluaciones> evaluacioneses = new HashSet<Evaluaciones>(0);

	public Alumnos() {
	}

	public Alumnos(BigInteger numAlumno) {
		this.numAlumno = numAlumno;
	}

	public Alumnos(BigInteger numAlumno, Cursos cursos, String nombre, String direccion, String tlf,
			BigDecimal notaMedia, Set<Evaluaciones> evaluacioneses) {
		this.numAlumno = numAlumno;
		this.cursos = cursos;
		this.nombre = nombre;
		this.direccion = direccion;
		this.tlf = tlf;
		this.notaMedia = notaMedia;
		this.evaluacioneses = evaluacioneses;
	}

	public BigInteger getNumAlumno() {
		return this.numAlumno;
	}

	public void setNumAlumno(BigInteger numAlumno) {
		this.numAlumno = numAlumno;
	}

	public Cursos getCursos() {
		return this.cursos;
	}

	public void setCursos(Cursos cursos) {
		this.cursos = cursos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTlf() {
		return this.tlf;
	}

	public void setTlf(String tlf) {
		this.tlf = tlf;
	}

	public BigDecimal getNotaMedia() {
		return this.notaMedia;
	}

	public void setNotaMedia(BigDecimal notaMedia) {
		this.notaMedia = notaMedia;
	}

	public Set<Evaluaciones> getEvaluacioneses() {
		return this.evaluacioneses;
	}

	public void setEvaluacioneses(Set<Evaluaciones> evaluacioneses) {
		this.evaluacioneses = evaluacioneses;
	}

}
