package datos;
// Generated 9 may 2023 17:23:53 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Asignaturas generated by hbm2java
 */
public class Asignaturas implements java.io.Serializable {

	private BigInteger codAsig;
	private Cursos cursos;
	private Departamentos departamentos;
	private String nombre;
	private Set<Evaluaciones> evaluacioneses = new HashSet<Evaluaciones>(0);

	public Asignaturas() {
	}

	public Asignaturas(BigInteger codAsig) {
		this.codAsig = codAsig;
	}

	public Asignaturas(BigInteger codAsig, Cursos cursos, Departamentos departamentos, String nombre,
			Set<Evaluaciones> evaluacioneses) {
		this.codAsig = codAsig;
		this.cursos = cursos;
		this.departamentos = departamentos;
		this.nombre = nombre;
		this.evaluacioneses = evaluacioneses;
	}

	public BigInteger getCodAsig() {
		return this.codAsig;
	}

	public void setCodAsig(BigInteger codAsig) {
		this.codAsig = codAsig;
	}

	public Cursos getCursos() {
		return this.cursos;
	}

	public void setCursos(Cursos cursos) {
		this.cursos = cursos;
	}

	public Departamentos getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Departamentos departamentos) {
		this.departamentos = departamentos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Evaluaciones> getEvaluacioneses() {
		return this.evaluacioneses;
	}

	public void setEvaluacioneses(Set<Evaluaciones> evaluacioneses) {
		this.evaluacioneses = evaluacioneses;
	}

}
