package datos;
// Generated 9 may 2023 17:23:53 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Centros generated by hbm2java
 */
public class Centros implements java.io.Serializable {

	private BigInteger codCentro;
	private String nombre;
	private String localidad;
	private String tlf;
	private BigInteger numAlumnos;
	private BigInteger numCursos;
	private BigInteger presupuesto;
	private Set<Cursos> cursoses = new HashSet<Cursos>(0);

	public Centros() {
	}

	public Centros(BigInteger codCentro) {
		this.codCentro = codCentro;
	}

	public Centros(BigInteger codCentro, String nombre, String localidad, String tlf, BigInteger numAlumnos,
			BigInteger numCursos, BigInteger presupuesto, Set<Cursos> cursoses) {
		this.codCentro = codCentro;
		this.nombre = nombre;
		this.localidad = localidad;
		this.tlf = tlf;
		this.numAlumnos = numAlumnos;
		this.numCursos = numCursos;
		this.presupuesto = presupuesto;
		this.cursoses = cursoses;
	}

	public BigInteger getCodCentro() {
		return this.codCentro;
	}

	public void setCodCentro(BigInteger codCentro) {
		this.codCentro = codCentro;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	public String getTlf() {
		return this.tlf;
	}

	public void setTlf(String tlf) {
		this.tlf = tlf;
	}

	public BigInteger getNumAlumnos() {
		return this.numAlumnos;
	}

	public void setNumAlumnos(BigInteger numAlumnos) {
		this.numAlumnos = numAlumnos;
	}

	public BigInteger getNumCursos() {
		return this.numCursos;
	}

	public void setNumCursos(BigInteger numCursos) {
		this.numCursos = numCursos;
	}

	public BigInteger getPresupuesto() {
		return this.presupuesto;
	}

	public void setPresupuesto(BigInteger presupuesto) {
		this.presupuesto = presupuesto;
	}

	public Set<Cursos> getCursoses() {
		return this.cursoses;
	}

	public void setCursoses(Set<Cursos> cursoses) {
		this.cursoses = cursoses;
	}

}
