package datos;
// Generated 9 may 2023 17:23:53 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Cursos generated by hbm2java
 */
public class Cursos implements java.io.Serializable {

	private BigInteger codCurso;
	private Centros centros;
	private String denominacion;
	private Integer costeMatricula;
	private BigInteger numAlumnos;
	private Set<Asignaturas> asignaturases = new HashSet<Asignaturas>(0);
	private Set<Alumnos> alumnoses = new HashSet<Alumnos>(0);

	public Cursos() {
	}

	public Cursos(BigInteger codCurso) {
		this.codCurso = codCurso;
	}

	public Cursos(BigInteger codCurso, Centros centros, String denominacion, Integer costeMatricula,
			BigInteger numAlumnos, Set<Asignaturas> asignaturases, Set<Alumnos> alumnoses) {
		this.codCurso = codCurso;
		this.centros = centros;
		this.denominacion = denominacion;
		this.costeMatricula = costeMatricula;
		this.numAlumnos = numAlumnos;
		this.asignaturases = asignaturases;
		this.alumnoses = alumnoses;
	}

	public BigInteger getCodCurso() {
		return this.codCurso;
	}

	public void setCodCurso(BigInteger codCurso) {
		this.codCurso = codCurso;
	}

	public Centros getCentros() {
		return this.centros;
	}

	public void setCentros(Centros centros) {
		this.centros = centros;
	}

	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	public Integer getCosteMatricula() {
		return this.costeMatricula;
	}

	public void setCosteMatricula(Integer costeMatricula) {
		this.costeMatricula = costeMatricula;
	}

	public BigInteger getNumAlumnos() {
		return this.numAlumnos;
	}

	public void setNumAlumnos(BigInteger numAlumnos) {
		this.numAlumnos = numAlumnos;
	}

	public Set<Asignaturas> getAsignaturases() {
		return this.asignaturases;
	}

	public void setAsignaturases(Set<Asignaturas> asignaturases) {
		this.asignaturases = asignaturases;
	}

	public Set<Alumnos> getAlumnoses() {
		return this.alumnoses;
	}

	public void setAlumnoses(Set<Alumnos> alumnoses) {
		this.alumnoses = alumnoses;
	}

}
