package datos;
// Generated 9 may 2023 17:23:53 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos implements java.io.Serializable {

	private BigInteger codDepar;
	private String nombreDepar;
	private BigInteger numAsig;
	private Set<Asignaturas> asignaturases = new HashSet<Asignaturas>(0);

	public Departamentos() {
	}

	public Departamentos(BigInteger codDepar) {
		this.codDepar = codDepar;
	}

	public Departamentos(BigInteger codDepar, String nombreDepar, BigInteger numAsig, Set<Asignaturas> asignaturases) {
		this.codDepar = codDepar;
		this.nombreDepar = nombreDepar;
		this.numAsig = numAsig;
		this.asignaturases = asignaturases;
	}

	public BigInteger getCodDepar() {
		return this.codDepar;
	}

	public void setCodDepar(BigInteger codDepar) {
		this.codDepar = codDepar;
	}

	public String getNombreDepar() {
		return this.nombreDepar;
	}

	public void setNombreDepar(String nombreDepar) {
		this.nombreDepar = nombreDepar;
	}

	public BigInteger getNumAsig() {
		return this.numAsig;
	}

	public void setNumAsig(BigInteger numAsig) {
		this.numAsig = numAsig;
	}

	public Set<Asignaturas> getAsignaturases() {
		return this.asignaturases;
	}

	public void setAsignaturases(Set<Asignaturas> asignaturases) {
		this.asignaturases = asignaturases;
	}

}
