package datos;
// Generated 15 nov 2022 19:49:34 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compras generated by hbm2java
 */
public class Compras implements java.io.Serializable {

	private int numcompra;
	private Clientes clientes;
	private Date fecha;
	private Integer descuento;
	private Set<Detcompras> detcomprases = new HashSet<Detcompras>(0);

	public Compras() {
	}

	public Compras(int numcompra, Clientes clientes) {
		this.numcompra = numcompra;
		this.clientes = clientes;
	}

	public Compras(int numcompra, Clientes clientes, Date fecha, Integer descuento, Set<Detcompras> detcomprases) {
		this.numcompra = numcompra;
		this.clientes = clientes;
		this.fecha = fecha;
		this.descuento = descuento;
		this.detcomprases = detcomprases;
	}

	public int getNumcompra() {
		return this.numcompra;
	}

	public void setNumcompra(int numcompra) {
		this.numcompra = numcompra;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Integer getDescuento() {
		return this.descuento;
	}

	public void setDescuento(Integer descuento) {
		this.descuento = descuento;
	}

	public Set<Detcompras> getDetcomprases() {
		return this.detcomprases;
	}

	public void setDetcomprases(Set<Detcompras> detcomprases) {
		this.detcomprases = detcomprases;
	}

}
