package datos;
// Generated 15 nov 2022 19:49:34 by Hibernate Tools 4.3.6.Final

/**
 * Detcompras generated by hbm2java
 */
public class Detcompras implements java.io.Serializable {

	private DetcomprasId id;
	private Compras compras;
	private Productos productos;
	private Integer unidades;

	public Detcompras() {
	}

	public Detcompras(DetcomprasId id, Compras compras, Productos productos) {
		this.id = id;
		this.compras = compras;
		this.productos = productos;
	}

	public Detcompras(DetcomprasId id, Compras compras, Productos productos, Integer unidades) {
		this.id = id;
		this.compras = compras;
		this.productos = productos;
		this.unidades = unidades;
	}

	public DetcomprasId getId() {
		return this.id;
	}

	public void setId(DetcomprasId id) {
		this.id = id;
	}

	public Compras getCompras() {
		return this.compras;
	}

	public void setCompras(Compras compras) {
		this.compras = compras;
	}

	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

	public Integer getUnidades() {
		return this.unidades;
	}

	public void setUnidades(Integer unidades) {
		this.unidades = unidades;
	}

}
