package datos;
// Generated 15 nov 2022 19:49:34 by Hibernate Tools 4.3.6.Final

/**
 * DetcomprasId generated by hbm2java
 */
public class DetcomprasId implements java.io.Serializable {

	private int numcompra;
	private int codproducto;

	public DetcomprasId() {
	}

	public DetcomprasId(int numcompra, int codproducto) {
		this.numcompra = numcompra;
		this.codproducto = codproducto;
	}

	public int getNumcompra() {
		return this.numcompra;
	}

	public void setNumcompra(int numcompra) {
		this.numcompra = numcompra;
	}

	public int getCodproducto() {
		return this.codproducto;
	}

	public void setCodproducto(int codproducto) {
		this.codproducto = codproducto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetcomprasId))
			return false;
		DetcomprasId castOther = (DetcomprasId) other;

		return (this.getNumcompra() == castOther.getNumcompra())
				&& (this.getCodproducto() == castOther.getCodproducto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumcompra();
		result = 37 * result + this.getCodproducto();
		return result;
	}

}
