package datos;
// Generated 15 nov 2022 19:49:34 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos implements java.io.Serializable {

	private int codproducto;
	private String denominacion;
	private String tipo;
	private Float pvp;
	private Integer stock;
	private Set<Detcompras> detcomprases = new HashSet<Detcompras>(0);

	public Productos() {
	}

	public Productos(int codproducto) {
		this.codproducto = codproducto;
	}

	public Productos(int codproducto, String denominacion, String tipo, Float pvp, Integer stock,
			Set<Detcompras> detcomprases) {
		this.codproducto = codproducto;
		this.denominacion = denominacion;
		this.tipo = tipo;
		this.pvp = pvp;
		this.stock = stock;
		this.detcomprases = detcomprases;
	}

	public int getCodproducto() {
		return this.codproducto;
	}

	public void setCodproducto(int codproducto) {
		this.codproducto = codproducto;
	}

	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Float getPvp() {
		return this.pvp;
	}

	public void setPvp(Float pvp) {
		this.pvp = pvp;
	}

	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	public Set<Detcompras> getDetcomprases() {
		return this.detcomprases;
	}

	public void setDetcomprases(Set<Detcompras> detcomprases) {
		this.detcomprases = detcomprases;
	}

}
