package datos;
// Generated 12 dic 2022 1:26:44 by Hibernate Tools 4.3.6.Final

/**
 * TAccesos generated by hbm2java
 */
public class TAccesos implements java.io.Serializable {

	private int codAcceso;
	private String descripcion;
	private int codEstacion;

	public TAccesos() {
	}

	public TAccesos(int codAcceso, String descripcion, int codEstacion) {
		this.codAcceso = codAcceso;
		this.descripcion = descripcion;
		this.codEstacion = codEstacion;
	}

	public int getCodAcceso() {
		return this.codAcceso;
	}

	public void setCodAcceso(int codAcceso) {
		this.codAcceso = codAcceso;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public int getCodEstacion() {
		return this.codEstacion;
	}

	public void setCodEstacion(int codEstacion) {
		this.codEstacion = codEstacion;
	}

}
