package datos;
// Generated 15 nov 2022 19:41:49 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TEstaciones generated by hbm2java
 */
public class TEstaciones implements java.io.Serializable {

	private int codEstacion;
	private String nombre;
	private String direccion;
	private Set<TLineaEstacion> TLineaEstacions = new HashSet<TLineaEstacion>(0);
	private Set<TAccesos> TAccesoses = new HashSet<TAccesos>(0);

	public TEstaciones() {
	}

	public TEstaciones(int codEstacion, String nombre, String direccion) {
		this.codEstacion = codEstacion;
		this.nombre = nombre;
		this.direccion = direccion;
	}

	public TEstaciones(int codEstacion, String nombre, String direccion, Set<TLineaEstacion> TLineaEstacions,
			Set<TAccesos> TAccesoses) {
		this.codEstacion = codEstacion;
		this.nombre = nombre;
		this.direccion = direccion;
		this.TLineaEstacions = TLineaEstacions;
		this.TAccesoses = TAccesoses;
	}

	public int getCodEstacion() {
		return this.codEstacion;
	}

	public void setCodEstacion(int codEstacion) {
		this.codEstacion = codEstacion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Set<TLineaEstacion> getTLineaEstacions() {
		return this.TLineaEstacions;
	}

	public void setTLineaEstacions(Set<TLineaEstacion> TLineaEstacions) {
		this.TLineaEstacions = TLineaEstacions;
	}

	public Set<TAccesos> getTAccesoses() {
		return this.TAccesoses;
	}

	public void setTAccesoses(Set<TAccesos> TAccesoses) {
		this.TAccesoses = TAccesoses;
	}

}
