package datos;
// Generated 15 nov 2022 19:41:49 by Hibernate Tools 4.3.6.Final

/**
 * TLineaEstacion generated by hbm2java
 */
public class TLineaEstacion implements java.io.Serializable {

	private TLineaEstacionId id;
	private TEstaciones TEstaciones;
	private TLineas TLineas;
	private int orden;

	public TLineaEstacion() {
	}

	public TLineaEstacion(TLineaEstacionId id, TEstaciones TEstaciones, TLineas TLineas, int orden) {
		this.id = id;
		this.TEstaciones = TEstaciones;
		this.TLineas = TLineas;
		this.orden = orden;
	}

	public TLineaEstacionId getId() {
		return this.id;
	}

	public void setId(TLineaEstacionId id) {
		this.id = id;
	}

	public TEstaciones getTEstaciones() {
		return this.TEstaciones;
	}

	public void setTEstaciones(TEstaciones TEstaciones) {
		this.TEstaciones = TEstaciones;
	}

	public TLineas getTLineas() {
		return this.TLineas;
	}

	public void setTLineas(TLineas TLineas) {
		this.TLineas = TLineas;
	}

	public int getOrden() {
		return this.orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

}
