package datos;
// Generated 15 nov 2022 12:59:08 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;

/**
 * EstadisticasId generated by hbm2java
 */
public class EstadisticasId implements java.io.Serializable {

	private String temporada;
	private BigInteger jugador;

	public EstadisticasId() {
	}

	public EstadisticasId(String temporada, BigInteger jugador) {
		this.temporada = temporada;
		this.jugador = jugador;
	}

	public String getTemporada() {
		return this.temporada;
	}

	public void setTemporada(String temporada) {
		this.temporada = temporada;
	}

	public BigInteger getJugador() {
		return this.jugador;
	}

	public void setJugador(BigInteger jugador) {
		this.jugador = jugador;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EstadisticasId))
			return false;
		EstadisticasId castOther = (EstadisticasId) other;

		return ((this.getTemporada() == castOther.getTemporada()) || (this.getTemporada() != null
				&& castOther.getTemporada() != null && this.getTemporada().equals(castOther.getTemporada())))
				&& ((this.getJugador() == castOther.getJugador()) || (this.getJugador() != null
						&& castOther.getJugador() != null && this.getJugador().equals(castOther.getJugador())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTemporada() == null ? 0 : this.getTemporada().hashCode());
		result = 37 * result + (getJugador() == null ? 0 : this.getJugador().hashCode());
		return result;
	}

}
