package datos;
// Generated 15 nov 2022 12:59:08 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Jugadores generated by hbm2java
 */
public class Jugadores implements java.io.Serializable {

	private BigInteger codigo;
	private Equipos equipos;
	private String nombre;
	private String procedencia;
	private String altura;
	private BigInteger peso;
	private String posicion;
	private Set<Estadisticas> estadisticases = new HashSet<Estadisticas>(0);

	public Jugadores() {
	}

	public Jugadores(BigInteger codigo) {
		this.codigo = codigo;
	}

	public Jugadores(BigInteger codigo, Equipos equipos, String nombre, String procedencia, String altura,
			BigInteger peso, String posicion, Set<Estadisticas> estadisticases) {
		this.codigo = codigo;
		this.equipos = equipos;
		this.nombre = nombre;
		this.procedencia = procedencia;
		this.altura = altura;
		this.peso = peso;
		this.posicion = posicion;
		this.estadisticases = estadisticases;
	}

	public BigInteger getCodigo() {
		return this.codigo;
	}

	public void setCodigo(BigInteger codigo) {
		this.codigo = codigo;
	}

	public Equipos getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Equipos equipos) {
		this.equipos = equipos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getProcedencia() {
		return this.procedencia;
	}

	public void setProcedencia(String procedencia) {
		this.procedencia = procedencia;
	}

	public String getAltura() {
		return this.altura;
	}

	public void setAltura(String altura) {
		this.altura = altura;
	}

	public BigInteger getPeso() {
		return this.peso;
	}

	public void setPeso(BigInteger peso) {
		this.peso = peso;
	}

	public String getPosicion() {
		return this.posicion;
	}

	public void setPosicion(String posicion) {
		this.posicion = posicion;
	}

	public Set<Estadisticas> getEstadisticases() {
		return this.estadisticases;
	}

	public void setEstadisticases(Set<Estadisticas> estadisticases) {
		this.estadisticases = estadisticases;
	}

}
