package datos;
// Generated 15 nov 2022 19:32:23 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * C1Asignaturas generated by hbm2java
 */
public class C1Asignaturas implements java.io.Serializable {

	private String codAsig;
	private String nombreAsi;
	private Set<C1Profesores> c1Profesoreses = new HashSet<C1Profesores>(0);

	public C1Asignaturas() {
	}

	public C1Asignaturas(String codAsig) {
		this.codAsig = codAsig;
	}

	public C1Asignaturas(String codAsig, String nombreAsi, Set<C1Profesores> c1Profesoreses) {
		this.codAsig = codAsig;
		this.nombreAsi = nombreAsi;
		this.c1Profesoreses = c1Profesoreses;
	}

	public String getCodAsig() {
		return this.codAsig;
	}

	public void setCodAsig(String codAsig) {
		this.codAsig = codAsig;
	}

	public String getNombreAsi() {
		return this.nombreAsi;
	}

	public void setNombreAsi(String nombreAsi) {
		this.nombreAsi = nombreAsi;
	}

	public Set<C1Profesores> getC1Profesoreses() {
		return this.c1Profesoreses;
	}

	public void setC1Profesoreses(Set<C1Profesores> c1Profesoreses) {
		this.c1Profesoreses = c1Profesoreses;
	}

}
