package datos;
// Generated 17 nov 2022 11:20:23 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Alumnos generated by hbm2java
 */
public class Alumnos implements java.io.Serializable {

	private String dni;
	private String apenom;
	private String direc;
	private String pobla;
	private String telef;
	private Set<Notas> notases = new HashSet<Notas>(0);

	public Alumnos() {
	}

	public Alumnos(String dni) {
		this.dni = dni;
	}

	public Alumnos(String dni, String apenom, String direc, String pobla, String telef, Set<Notas> notases) {
		this.dni = dni;
		this.apenom = apenom;
		this.direc = direc;
		this.pobla = pobla;
		this.telef = telef;
		this.notases = notases;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getApenom() {
		return this.apenom;
	}

	public void setApenom(String apenom) {
		this.apenom = apenom;
	}

	public String getDirec() {
		return this.direc;
	}

	public void setDirec(String direc) {
		this.direc = direc;
	}

	public String getPobla() {
		return this.pobla;
	}

	public void setPobla(String pobla) {
		this.pobla = pobla;
	}

	public String getTelef() {
		return this.telef;
	}

	public void setTelef(String telef) {
		this.telef = telef;
	}

	public Set<Notas> getNotases() {
		return this.notases;
	}

	public void setNotases(Set<Notas> notases) {
		this.notases = notases;
	}

}
