package datos;
// Generated 17 nov 2022 11:20:23 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Asignaturas generated by hbm2java
 */
public class Asignaturas implements java.io.Serializable {

	private int cod;
	private String nombre;
	private Set<Notas> notases = new HashSet<Notas>(0);

	public Asignaturas() {
	}

	public Asignaturas(int cod) {
		this.cod = cod;
	}

	public Asignaturas(int cod, String nombre, Set<Notas> notases) {
		this.cod = cod;
		this.nombre = nombre;
		this.notases = notases;
	}

	public int getCod() {
		return this.cod;
	}

	public void setCod(int cod) {
		this.cod = cod;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Notas> getNotases() {
		return this.notases;
	}

	public void setNotases(Set<Notas> notases) {
		this.notases = notases;
	}

}
