package datos;
// Generated 17 nov 2022 11:20:23 by Hibernate Tools 4.3.6.Final

/**
 * Doscampos generated by hbm2java
 */
public class Doscampos implements java.io.Serializable {

	private DoscamposId id;
	private Departamentos departamentos;
	private Empleados empleados;
	private String cad;

	public Doscampos() {
	}

	public Doscampos(DoscamposId id, Departamentos departamentos, Empleados empleados) {
		this.id = id;
		this.departamentos = departamentos;
		this.empleados = empleados;
	}

	public Doscampos(DoscamposId id, Departamentos departamentos, Empleados empleados, String cad) {
		this.id = id;
		this.departamentos = departamentos;
		this.empleados = empleados;
		this.cad = cad;
	}

	public DoscamposId getId() {
		return this.id;
	}

	public void setId(DoscamposId id) {
		this.id = id;
	}

	public Departamentos getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Departamentos departamentos) {
		this.departamentos = departamentos;
	}

	public Empleados getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Empleados empleados) {
		this.empleados = empleados;
	}

	public String getCad() {
		return this.cad;
	}

	public void setCad(String cad) {
		this.cad = cad;
	}

}
