package datos;
// Generated 17 nov 2022 11:20:23 by Hibernate Tools 4.3.6.Final

/**
 * DoscamposId generated by hbm2java
 */
public class DoscamposId implements java.io.Serializable {

	private byte deptNo;
	private short empNo;

	public DoscamposId() {
	}

	public DoscamposId(byte deptNo, short empNo) {
		this.deptNo = deptNo;
		this.empNo = empNo;
	}

	public byte getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(byte deptNo) {
		this.deptNo = deptNo;
	}

	public short getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(short empNo) {
		this.empNo = empNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DoscamposId))
			return false;
		DoscamposId castOther = (DoscamposId) other;

		return (this.getDeptNo() == castOther.getDeptNo()) && (this.getEmpNo() == castOther.getEmpNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDeptNo();
		result = 37 * result + this.getEmpNo();
		return result;
	}

}
