package datos;
// Generated 17 nov 2022 11:20:23 by Hibernate Tools 4.3.6.Final

/**
 * NotasId generated by hbm2java
 */
public class NotasId implements java.io.Serializable {

	private String dni;
	private int cod;

	public NotasId() {
	}

	public NotasId(String dni, int cod) {
		this.dni = dni;
		this.cod = cod;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public int getCod() {
		return this.cod;
	}

	public void setCod(int cod) {
		this.cod = cod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NotasId))
			return false;
		NotasId castOther = (NotasId) other;

		return ((this.getDni() == castOther.getDni())
				|| (this.getDni() != null && castOther.getDni() != null && this.getDni().equals(castOther.getDni())))
				&& (this.getCod() == castOther.getCod());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDni() == null ? 0 : this.getDni().hashCode());
		result = 37 * result + this.getCod();
		return result;
	}

}
