package datos;
// Generated 17 nov 2022 11:20:23 by Hibernate Tools 4.3.6.Final

/**
 * Tabla1Id generated by hbm2java
 */
public class Tabla1Id implements java.io.Serializable {

	private String nom;
	private Integer ed;

	public Tabla1Id() {
	}

	public Tabla1Id(String nom, Integer ed) {
		this.nom = nom;
		this.ed = ed;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Integer getEd() {
		return this.ed;
	}

	public void setEd(Integer ed) {
		this.ed = ed;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Tabla1Id))
			return false;
		Tabla1Id castOther = (Tabla1Id) other;

		return ((this.getNom() == castOther.getNom())
				|| (this.getNom() != null && castOther.getNom() != null && this.getNom().equals(castOther.getNom())))
				&& ((this.getEd() == castOther.getEd()) || (this.getEd() != null && castOther.getEd() != null
						&& this.getEd().equals(castOther.getEd())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNom() == null ? 0 : this.getNom().hashCode());
		result = 37 * result + (getEd() == null ? 0 : this.getEd().hashCode());
		return result;
	}

}
