package datos;
// Generated 17 nov 2022 11:20:23 by Hibernate Tools 4.3.6.Final

/**
 * Tabla1 generated by hbm2java
 */
public class Tabla1 implements java.io.Serializable {

	private Tabla1Id id;

	public Tabla1() {
	}

	public Tabla1(Tabla1Id id) {
		this.id = id;
	}

	public Tabla1Id getId() {
		return this.id;
	}

	public void setId(Tabla1Id id) {
		this.id = id;
	}

}
