package datos;
// Generated 17 nov 2022 11:20:23 by Hibernate Tools 4.3.6.Final

/**
 * TotalesId generated by hbm2java
 */
public class TotalesId implements java.io.Serializable {

	private byte dep;
	private String dnombre;
	private long nemp;
	private Double media;

	public TotalesId() {
	}

	public TotalesId(byte dep, long nemp) {
		this.dep = dep;
		this.nemp = nemp;
	}

	public TotalesId(byte dep, String dnombre, long nemp, Double media) {
		this.dep = dep;
		this.dnombre = dnombre;
		this.nemp = nemp;
		this.media = media;
	}

	public byte getDep() {
		return this.dep;
	}

	public void setDep(byte dep) {
		this.dep = dep;
	}

	public String getDnombre() {
		return this.dnombre;
	}

	public void setDnombre(String dnombre) {
		this.dnombre = dnombre;
	}

	public long getNemp() {
		return this.nemp;
	}

	public void setNemp(long nemp) {
		this.nemp = nemp;
	}

	public Double getMedia() {
		return this.media;
	}

	public void setMedia(Double media) {
		this.media = media;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TotalesId))
			return false;
		TotalesId castOther = (TotalesId) other;

		return (this.getDep() == castOther.getDep())
				&& ((this.getDnombre() == castOther.getDnombre()) || (this.getDnombre() != null
						&& castOther.getDnombre() != null && this.getDnombre().equals(castOther.getDnombre())))
				&& (this.getNemp() == castOther.getNemp())
				&& ((this.getMedia() == castOther.getMedia()) || (this.getMedia() != null
						&& castOther.getMedia() != null && this.getMedia().equals(castOther.getMedia())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDep();
		result = 37 * result + (getDnombre() == null ? 0 : this.getDnombre().hashCode());
		result = 37 * result + (int) this.getNemp();
		result = 37 * result + (getMedia() == null ? 0 : this.getMedia().hashCode());
		return result;
	}

}
