package datos;
// Generated 17 nov 2022 11:20:23 by Hibernate Tools 4.3.6.Final

/**
 * Totales generated by hbm2java
 */
public class Totales implements java.io.Serializable {

	private TotalesId id;

	public Totales() {
	}

	public Totales(TotalesId id) {
		this.id = id;
	}

	public TotalesId getId() {
		return this.id;
	}

	public void setId(TotalesId id) {
		this.id = id;
	}

}
