package datos;
// Generated 22 nov 2022 12:25:42 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos implements java.io.Serializable {

	private short id;
	private String descripcion;
	private Short stockactual;
	private Short stockminimo;
	private BigDecimal pvp;
	private Set<Ventas> ventases = new HashSet<Ventas>(0);

	public Productos() {
	}

	public Productos(short id, String descripcion) {
		this.id = id;
		this.descripcion = descripcion;
	}

	public Productos(short id, String descripcion, Short stockactual, Short stockminimo, BigDecimal pvp,
			Set<Ventas> ventases) {
		this.id = id;
		this.descripcion = descripcion;
		this.stockactual = stockactual;
		this.stockminimo = stockminimo;
		this.pvp = pvp;
		this.ventases = ventases;
	}

	public short getId() {
		return this.id;
	}

	public void setId(short id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Short getStockactual() {
		return this.stockactual;
	}

	public void setStockactual(Short stockactual) {
		this.stockactual = stockactual;
	}

	public Short getStockminimo() {
		return this.stockminimo;
	}

	public void setStockminimo(Short stockminimo) {
		this.stockminimo = stockminimo;
	}

	public BigDecimal getPvp() {
		return this.pvp;
	}

	public void setPvp(BigDecimal pvp) {
		this.pvp = pvp;
	}

	public Set<Ventas> getVentases() {
		return this.ventases;
	}

	public void setVentases(Set<Ventas> ventases) {
		this.ventases = ventases;
	}

}
