package datos;
// Generated 22 nov 2022 12:25:42 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Tclientes generated by hbm2java
 */
public class Tclientes implements java.io.Serializable {

	private String idcliente;
	private String nombre;
	private String direccion;
	private String poblacion;
	private String codpostal;
	private String provincia;
	private String nif;
	private String telefono1;
	private String telefono2;
	private String telefono3;
	private Set<Tventas> tventases = new HashSet<Tventas>(0);

	public Tclientes() {
	}

	public Tclientes(String idcliente) {
		this.idcliente = idcliente;
	}

	public Tclientes(String idcliente, String nombre, String direccion, String poblacion, String codpostal,
			String provincia, String nif, String telefono1, String telefono2, String telefono3,
			Set<Tventas> tventases) {
		this.idcliente = idcliente;
		this.nombre = nombre;
		this.direccion = direccion;
		this.poblacion = poblacion;
		this.codpostal = codpostal;
		this.provincia = provincia;
		this.nif = nif;
		this.telefono1 = telefono1;
		this.telefono2 = telefono2;
		this.telefono3 = telefono3;
		this.tventases = tventases;
	}

	public String getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(String idcliente) {
		this.idcliente = idcliente;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	public String getCodpostal() {
		return this.codpostal;
	}

	public void setCodpostal(String codpostal) {
		this.codpostal = codpostal;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	public String getTelefono1() {
		return this.telefono1;
	}

	public void setTelefono1(String telefono1) {
		this.telefono1 = telefono1;
	}

	public String getTelefono2() {
		return this.telefono2;
	}

	public void setTelefono2(String telefono2) {
		this.telefono2 = telefono2;
	}

	public String getTelefono3() {
		return this.telefono3;
	}

	public void setTelefono3(String telefono3) {
		this.telefono3 = telefono3;
	}

	public Set<Tventas> getTventases() {
		return this.tventases;
	}

	public void setTventases(Set<Tventas> tventases) {
		this.tventases = tventases;
	}

}
