package datos;
// Generated 22 nov 2022 12:25:42 by Hibernate Tools 4.3.6.Final

/**
 * TlineasventasId generated by hbm2java
 */
public class TlineasventasId implements java.io.Serializable {

	private String idventa;
	private short numerolinea;

	public TlineasventasId() {
	}

	public TlineasventasId(String idventa, short numerolinea) {
		this.idventa = idventa;
		this.numerolinea = numerolinea;
	}

	public String getIdventa() {
		return this.idventa;
	}

	public void setIdventa(String idventa) {
		this.idventa = idventa;
	}

	public short getNumerolinea() {
		return this.numerolinea;
	}

	public void setNumerolinea(short numerolinea) {
		this.numerolinea = numerolinea;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TlineasventasId))
			return false;
		TlineasventasId castOther = (TlineasventasId) other;

		return ((this.getIdventa() == castOther.getIdventa()) || (this.getIdventa() != null
				&& castOther.getIdventa() != null && this.getIdventa().equals(castOther.getIdventa())))
				&& (this.getNumerolinea() == castOther.getNumerolinea());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdventa() == null ? 0 : this.getIdventa().hashCode());
		result = 37 * result + this.getNumerolinea();
		return result;
	}

}
