package datos;
// Generated 22 nov 2022 12:25:42 by Hibernate Tools 4.3.6.Final

/**
 * Tlineasventas generated by hbm2java
 */
public class Tlineasventas implements java.io.Serializable {

	private TlineasventasId id;
	private Tproductos tproductos;
	private Tventas tventas;
	private Short cantidad;

	public Tlineasventas() {
	}

	public Tlineasventas(TlineasventasId id, Tventas tventas) {
		this.id = id;
		this.tventas = tventas;
	}

	public Tlineasventas(TlineasventasId id, Tproductos tproductos, Tventas tventas, Short cantidad) {
		this.id = id;
		this.tproductos = tproductos;
		this.tventas = tventas;
		this.cantidad = cantidad;
	}

	public TlineasventasId getId() {
		return this.id;
	}

	public void setId(TlineasventasId id) {
		this.id = id;
	}

	public Tproductos getTproductos() {
		return this.tproductos;
	}

	public void setTproductos(Tproductos tproductos) {
		this.tproductos = tproductos;
	}

	public Tventas getTventas() {
		return this.tventas;
	}

	public void setTventas(Tventas tventas) {
		this.tventas = tventas;
	}

	public Short getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Short cantidad) {
		this.cantidad = cantidad;
	}

}
