package datos;
// Generated 22 nov 2022 12:25:42 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tproductos generated by hbm2java
 */
public class Tproductos implements java.io.Serializable {

	private String idproducto;
	private String descripcion;
	private BigDecimal pvp;
	private Short stockactual;
	private Short stockminimo;
	private Set<Tlineasventas> tlineasventases = new HashSet<Tlineasventas>(0);

	public Tproductos() {
	}

	public Tproductos(String idproducto) {
		this.idproducto = idproducto;
	}

	public Tproductos(String idproducto, String descripcion, BigDecimal pvp, Short stockactual, Short stockminimo,
			Set<Tlineasventas> tlineasventases) {
		this.idproducto = idproducto;
		this.descripcion = descripcion;
		this.pvp = pvp;
		this.stockactual = stockactual;
		this.stockminimo = stockminimo;
		this.tlineasventases = tlineasventases;
	}

	public String getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(String idproducto) {
		this.idproducto = idproducto;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public BigDecimal getPvp() {
		return this.pvp;
	}

	public void setPvp(BigDecimal pvp) {
		this.pvp = pvp;
	}

	public Short getStockactual() {
		return this.stockactual;
	}

	public void setStockactual(Short stockactual) {
		this.stockactual = stockactual;
	}

	public Short getStockminimo() {
		return this.stockminimo;
	}

	public void setStockminimo(Short stockminimo) {
		this.stockminimo = stockminimo;
	}

	public Set<Tlineasventas> getTlineasventases() {
		return this.tlineasventases;
	}

	public void setTlineasventases(Set<Tlineasventas> tlineasventases) {
		this.tlineasventases = tlineasventases;
	}

}
