package datos;
// Generated 22 nov 2022 12:25:42 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tventas generated by hbm2java
 */
public class Tventas implements java.io.Serializable {

	private String idventa;
	private Tclientes tclientes;
	private Date fechaventa;
	private Set<Tlineasventas> tlineasventases = new HashSet<Tlineasventas>(0);

	public Tventas() {
	}

	public Tventas(String idventa, Tclientes tclientes) {
		this.idventa = idventa;
		this.tclientes = tclientes;
	}

	public Tventas(String idventa, Tclientes tclientes, Date fechaventa, Set<Tlineasventas> tlineasventases) {
		this.idventa = idventa;
		this.tclientes = tclientes;
		this.fechaventa = fechaventa;
		this.tlineasventases = tlineasventases;
	}

	public String getIdventa() {
		return this.idventa;
	}

	public void setIdventa(String idventa) {
		this.idventa = idventa;
	}

	public Tclientes getTclientes() {
		return this.tclientes;
	}

	public void setTclientes(Tclientes tclientes) {
		this.tclientes = tclientes;
	}

	public Date getFechaventa() {
		return this.fechaventa;
	}

	public void setFechaventa(Date fechaventa) {
		this.fechaventa = fechaventa;
	}

	public Set<Tlineasventas> getTlineasventases() {
		return this.tlineasventases;
	}

	public void setTlineasventases(Set<Tlineasventas> tlineasventases) {
		this.tlineasventases = tlineasventases;
	}

}
