package datos;
// Generated 22 nov 2022 12:25:42 by Hibernate Tools 4.3.6.Final

import java.util.Date;

/**
 * Ventas generated by hbm2java
 */
public class Ventas implements java.io.Serializable {

	private int idventa;
	private Clientes clientes;
	private Productos productos;
	private Date fechaventa;
	private short cantidad;

	public Ventas() {
	}

	public Ventas(int idventa, Clientes clientes, Productos productos, Date fechaventa, short cantidad) {
		this.idventa = idventa;
		this.clientes = clientes;
		this.productos = productos;
		this.fechaventa = fechaventa;
		this.cantidad = cantidad;
	}

	public int getIdventa() {
		return this.idventa;
	}

	public void setIdventa(int idventa) {
		this.idventa = idventa;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

	public Date getFechaventa() {
		return this.fechaventa;
	}

	public void setFechaventa(Date fechaventa) {
		this.fechaventa = fechaventa;
	}

	public short getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(short cantidad) {
		this.cantidad = cantidad;
	}

}
