package datos;
// Generated 15 nov 2022 19:15:32 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;

/**
 * Detcompras generated by hbm2java
 */
public class Detcompras implements java.io.Serializable {

	private DetcomprasId id;
	private Productos productos;
	private Compras compras;
	private BigInteger unidades;

	public Detcompras() {
	}

	public Detcompras(DetcomprasId id, Productos productos, Compras compras) {
		this.id = id;
		this.productos = productos;
		this.compras = compras;
	}

	public Detcompras(DetcomprasId id, Productos productos, Compras compras, BigInteger unidades) {
		this.id = id;
		this.productos = productos;
		this.compras = compras;
		this.unidades = unidades;
	}

	public DetcomprasId getId() {
		return this.id;
	}

	public void setId(DetcomprasId id) {
		this.id = id;
	}

	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

	public Compras getCompras() {
		return this.compras;
	}

	public void setCompras(Compras compras) {
		this.compras = compras;
	}

	public BigInteger getUnidades() {
		return this.unidades;
	}

	public void setUnidades(BigInteger unidades) {
		this.unidades = unidades;
	}

}
